baseURL = 'https://zero-space-zeta.vercel.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'digitalgarden'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3